// Action types in their JSON form (the node's serde shape) and the borsh
// encoder that mirrors crates/keel-actions/src/action.rs. Variant order and
// field order MUST match the Rust definitions exactly; test/vectors.json
// (generated by `cargo test -p keel-actions`) pins them byte for byte.
import { Writer, hexToBytes } from "./borsh.ts";

export type Amount = bigint | number | string;
/** 32-byte address: hex string or byte array (the node's JSON uses arrays). */
export type Address = string | number[] | Uint8Array;
export type Hash32 = string | number[] | Uint8Array;
export type Side = "buy" | "sell";
export type OrderType = "limit" | "market";
export type Chain = "Bitcoin" | "Ethereum" | "Tron";
export type Role = "Validator" | "Observer" | "Arbitrator";
export type VoteChoice = "Yes" | "No" | "Abstain" | "Veto";
export type Ruling = "WinsSeller" | "WinsBuyer" | { Split: { buyer_bps: number } };
export type Proof =
  | "None"
  | { Bitcoin: { headers: (number[] | Uint8Array | string)[]; merkle_proof: number[] | Uint8Array | string; tx_index: number } }
  | { Ethereum: { proof: number[] | Uint8Array | string } };

export interface Transfer { to: Address; asset: string; amount: Amount; memo?: string | null }
export interface PlaceOrder {
  pair: string; side: Side; order_type: OrderType;
  price?: Amount | null; quantity?: Amount | null; quote_budget?: Amount | null; client_id?: Amount | null;
}
export interface HouseQuote { pair: string; bid?: [Amount, Amount] | null; ask?: [Amount, Amount] | null; valid_until: Amount }
export interface OfferSpec {
  side: Side; asset: string; fiat_currency: string; payment_method: string; margin_bps: number;
  fixed_price?: Amount | null; min_amount: Amount; max_amount: Amount; payment_window_secs: number;
  country?: string | null; min_tier: number; terms: string; instructions_hash: Hash32;
}
export interface StartTrade { offer_id: Amount; amount: Amount; fiat_amount: Amount; instructions_hash: Hash32 }
export interface DepositObservation {
  chain: Chain; asset: string; tx_hash: Hash32; index: number; deposit_index: Amount; amount: Amount;
  external_height: Amount; tip_height: Amount; proof: Proof;
}
export interface OutboundObservation {
  outbound_id: Amount; tx_hash: Hash32; external_height: Amount; tip_height: Amount; fee_paid: Amount; success: boolean;
}
export interface Withdraw { asset: string; to: string; amount: Amount }
export interface VaultRegistration {
  chain: Chain; epoch: Amount; public_key: number[] | Uint8Array | string; chain_code?: Hash32 | null;
  signers: Address[]; threshold: number;
}
export interface Bond { role: Role; amount: Amount; consensus_key?: Hash32 | null }
export interface SettleParty { owner: Address; account_type: string }
export interface PairConfig {
  symbol: string; base_asset: string; quote_asset: string; base_decimals: number; quote_decimals: number;
  tick_size: Amount; lot_size: Amount; min_notional: Amount; max_notional: Amount; taker_fee_bps: number;
  maker_fee_bps: number; enabled: boolean; house_maker_enabled: boolean; house_party: SettleParty; fee_party: SettleParty;
}
/** Raw bytes as hex, a byte array, or a Uint8Array. */
export type Bytes = string | number[] | Uint8Array;

export type ProposalKind =
  | { ParamChange: { key: string; value: Amount } }
  | { ListPair: PairConfig }
  | { DelistPair: { symbol: string } }
  | { RegisterAsset: { asset: string; decimals: number } }
  | { TreasurySpend: { to: Address; asset: string; amount: Amount } }
  | { SoftwareUpgrade: { version: string; height: Amount } }
  | { SetArbitrators: { members: Address[] } }
  | { SetAttesters: { members: Address[] } }
  | { SetObservers: { members: Address[]; threshold: number } }
  | { SetStableBasket: { asset: string; cap: Amount; enabled: boolean } }
  | { PauseModule: { module: string; until_height: Amount } }
  | "Text"
  | { SetBtcCheckpoint: { network: number; height: Amount; header: Bytes; period_start_time: number } }
  | { SetEthCheckpoint: { period: Amount; committee_root: Bytes; next_committee_root: Bytes | null; genesis_validators_root: Bytes; fork_version: Bytes; committee_size: number } }
  | { SetTokenContract: { asset: string; contract: Bytes } }
  | { SetParamAdmin: { admin: Address | null } };
export interface Proposal { title: string; description: string; kind: ProposalKind }

export type Action =
  | { Transfer: Transfer }
  | { PlaceOrder: PlaceOrder }
  | { CancelOrder: { order_id: Amount } }
  | { HouseQuote: HouseQuote }
  | { BuyBudget: { actions: Amount } }
  | { CreateOffer: OfferSpec }
  | { UpdateOffer: { offer_id: Amount; spec: OfferSpec } }
  | { PauseOffer: { offer_id: Amount; paused: boolean } }
  | { CloseOffer: { offer_id: Amount } }
  | { StartTrade: StartTrade }
  | { MarkPaid: { trade_id: Amount; proof_hash?: Hash32 | null } }
  | { ReleaseTrade: { trade_id: Amount } }
  | { CancelTrade: { trade_id: Amount } }
  | { OpenDispute: { trade_id: Amount; evidence_hash: Hash32 } }
  | { SubmitEvidence: { trade_id: Amount; evidence_hash: Hash32 } }
  | { RuleDispute: { trade_id: Amount; ruling: Ruling } }
  | { RequestDepositAddress: { chain: Chain } }
  | { ObserveDeposit: DepositObservation }
  | { ObserveOutbound: OutboundObservation }
  | { ReportNetworkFee: { chain: Chain; fee_rate: Amount } }
  | { Withdraw: Withdraw }
  | { RegisterVault: VaultRegistration }
  | { MintStable: { asset: string; amount: Amount } }
  | { BurnStable: { asset: string; amount: Amount } }
  | { Bond: Bond }
  | { Unbond: { role: Role; amount: Amount } }
  | { Delegate: { validator: Address; amount: Amount } }
  | { Undelegate: { validator: Address; amount: Amount } }
  | "ClaimRewards"
  | { Propose: Proposal }
  | { Vote: { proposal_id: Amount; choice: VoteChoice } }
  | { ExecuteProposal: { proposal_id: Amount } }
  | { Attest: { subject: Address; tier: number; expires_at: Amount } }
  /** Direct parameter change by the chain's `param_admin` (genesis-set, governance-revocable). */
  | { SetParam: { key: string; value: Amount } }
  | { LockBudget: { amount: Amount } }
  | { UnlockBudget: { amount: Amount } }
  | { AuthorizeSessionKey: { key: Address; scope: number; expires_at: number } }
  | { RevokeSessionKey: { key: Address } }
  | { RegisterLightningNode: { node_id: Bytes } }
  | { ObserveLightningDeposit: { invoice: string; preimage: Bytes; amount_msat: number } }
  | { ObserveLightningPayout: { outbound_id: Amount; preimage: Bytes | null; fee_paid_msat: number; success: boolean } }
  | { FundLightningPool: { amount: Amount; to: string } }
  | { AnnounceLightningSweep: { tx_hash: Bytes; amount: Amount } }
  | { SetClientFee: { p2p_bps: number; taker_bps: number; withdraw_bps: number } }
  | { RegisterCustodyVault: CustodyVaultRegistration }
  | { RequestCustodyAddress: { chain: Chain; custodian: Address } }
  | { ObserveCustodyDeposit: { custodian: Address; observation: DepositObservation } }
  | { WithdrawCustody: Withdraw };

export interface CustodyVaultRegistration {
  chain: Chain; epoch: Amount; public_key: number[] | Uint8Array | string; chain_code?: Hash32 | null; signer_url: string;
}

/** Session scope bits (`keel_actions::session_scope`). */
export const SESSION_SCOPE = { MARKETS: 1, P2P_MANAGE: 2 } as const;

const ACTION_VARIANTS = [
  "Transfer", "PlaceOrder", "CancelOrder", "HouseQuote", "BuyBudget", "CreateOffer", "UpdateOffer", "PauseOffer",
  "CloseOffer", "StartTrade", "MarkPaid", "ReleaseTrade", "CancelTrade", "OpenDispute", "SubmitEvidence",
  "RuleDispute", "RequestDepositAddress", "ObserveDeposit", "ObserveOutbound", "ReportNetworkFee", "Withdraw",
  "RegisterVault", "MintStable", "BurnStable", "Bond", "Unbond", "Delegate", "Undelegate", "ClaimRewards", "Propose",
  "Vote", "ExecuteProposal", "Attest", "SetParam", "LockBudget", "UnlockBudget", "AuthorizeSessionKey", "RevokeSessionKey",
  "RegisterLightningNode", "ObserveLightningDeposit", "ObserveLightningPayout", "FundLightningPool", "AnnounceLightningSweep",
  "SetClientFee", "RegisterCustodyVault", "RequestCustodyAddress", "ObserveCustodyDeposit", "WithdrawCustody",
] as const;
const CHAINS = ["Bitcoin", "Ethereum", "Tron"] as const;
const ROLES = ["Validator", "Observer", "Arbitrator"] as const;
const VOTES = ["Yes", "No", "Abstain", "Veto"] as const;
const PROPOSAL_KINDS = [
  "ParamChange", "ListPair", "DelistPair", "RegisterAsset", "TreasurySpend", "SoftwareUpgrade", "SetArbitrators",
  "SetAttesters", "SetObservers", "SetStableBasket", "PauseModule", "Text",
  "SetBtcCheckpoint", "SetEthCheckpoint", "SetTokenContract", "SetParamAdmin",
] as const;

export function toBytes(v: string | number[] | Uint8Array): Uint8Array {
  if (typeof v === "string") return hexToBytes(v);
  return v instanceof Uint8Array ? v : Uint8Array.from(v);
}

function variantOf(v: unknown): [string, unknown] {
  if (typeof v === "string") return [v, {}];
  if (v && typeof v === "object") {
    const keys = Object.keys(v as object);
    if (keys.length !== 1) throw new Error(`enum value must have exactly one key, got ${keys.join(",")}`);
    const k = keys[0]!;
    return [k, (v as Record<string, unknown>)[k]];
  }
  throw new Error("bad enum value");
}

function unitEnum(w: Writer, names: readonly string[], v: string): void {
  const i = names.indexOf(v);
  if (i < 0) throw new Error(`unknown variant ${v}`);
  w.u8(i);
}

function address(w: Writer, a: Address): void { w.fixed(toBytes(a), 32); }
function hash(w: Writer, h: Hash32): void { w.fixed(toBytes(h), 32); }
function side(w: Writer, s: Side): void { w.u8(s === "buy" ? 0 : 1); }
function pair(w: Writer, p: [Amount, Amount]): void { w.u128(p[0]); w.u128(p[1]); }

function offerSpec(w: Writer, o: OfferSpec): void {
  side(w, o.side); w.string(o.asset); w.string(o.fiat_currency); w.string(o.payment_method); w.i32(o.margin_bps);
  w.option(o.fixed_price, (x) => w.u128(x)); w.u128(o.min_amount); w.u128(o.max_amount); w.u32(o.payment_window_secs);
  w.option(o.country, (x) => w.string(x)); w.u8(o.min_tier); w.string(o.terms); hash(w, o.instructions_hash);
}

function settleParty(w: Writer, p: SettleParty): void { address(w, p.owner); w.string(p.account_type); }

function pairConfig(w: Writer, c: PairConfig): void {
  w.string(c.symbol); w.string(c.base_asset); w.string(c.quote_asset); w.u32(c.base_decimals); w.u32(c.quote_decimals);
  w.u128(c.tick_size); w.u128(c.lot_size); w.u128(c.min_notional); w.u128(c.max_notional); w.u32(c.taker_fee_bps);
  w.u32(c.maker_fee_bps); w.bool(c.enabled); w.bool(c.house_maker_enabled); settleParty(w, c.house_party); settleParty(w, c.fee_party);
}

function proposalKind(w: Writer, k: ProposalKind): void {
  const [name, body] = variantOf(k);
  unitEnum(w, PROPOSAL_KINDS, name);
  const b = body as Record<string, any>;
  switch (name) {
    case "ParamChange": w.string(b.key); w.u128(b.value); break;
    case "ListPair": pairConfig(w, b as PairConfig); break;
    case "DelistPair": w.string(b.symbol); break;
    case "RegisterAsset": w.string(b.asset); w.u32(b.decimals); break;
    case "TreasurySpend": address(w, b.to); w.string(b.asset); w.u128(b.amount); break;
    case "SoftwareUpgrade": w.string(b.version); w.u64(b.height); break;
    case "SetArbitrators": case "SetAttesters": w.vec(b.members as Address[], (m) => address(w, m)); break;
    case "SetObservers": w.vec(b.members as Address[], (m) => address(w, m)); w.u32(b.threshold); break;
    case "SetStableBasket": w.string(b.asset); w.u128(b.cap); w.bool(b.enabled); break;
    case "PauseModule": w.string(b.module); w.u64(b.until_height); break;
    case "Text": break;
    case "SetBtcCheckpoint": w.u8(b.network); w.u64(b.height); w.vecU8(toBytes(b.header)); w.u32(b.period_start_time); break;
    case "SetEthCheckpoint":
      w.u64(b.period); w.fixed(toBytes(b.committee_root), 32);
      if (b.next_committee_root == null) w.u8(0); else { w.u8(1); w.fixed(toBytes(b.next_committee_root), 32); }
      w.fixed(toBytes(b.genesis_validators_root), 32); w.fixed(toBytes(b.fork_version), 4); w.u32(b.committee_size); break;
    case "SetTokenContract": w.string(b.asset); w.vecU8(toBytes(b.contract)); break;
    case "SetParamAdmin": if (b.admin == null) w.u8(0); else { w.u8(1); address(w, b.admin); } break;
  }
}

function proof(w: Writer, p: Proof): void {
  const [name, body] = variantOf(p);
  const b = body as Record<string, any>;
  switch (name) {
    case "None": w.u8(0); break;
    case "Bitcoin":
      w.u8(1);
      w.vec(b.headers as (number[] | Uint8Array | string)[], (h) => w.vecU8(toBytes(h)));
      w.vecU8(toBytes(b.merkle_proof)); w.u32(b.tx_index);
      break;
    case "Ethereum": w.u8(2); w.vecU8(toBytes(b.proof)); break;
    default: throw new Error(`unknown proof ${name}`);
  }
}

/** Borsh-encode an action exactly as the chain does. */
export function encodeAction(action: Action, w: Writer = new Writer()): Writer {
  const [name, body] = variantOf(action);
  unitEnum(w, ACTION_VARIANTS, name);
  const b = body as Record<string, any>;
  switch (name) {
    case "Transfer": address(w, b.to); w.string(b.asset); w.u128(b.amount); w.option(b.memo, (m) => w.string(m)); break;
    case "PlaceOrder":
      w.string(b.pair); side(w, b.side); w.u8(b.order_type === "limit" ? 0 : 1);
      w.option(b.price, (x) => w.u128(x)); w.option(b.quantity, (x) => w.u128(x));
      w.option(b.quote_budget, (x) => w.u128(x)); w.option(b.client_id, (x) => w.u64(x));
      break;
    case "CancelOrder": w.u64(b.order_id); break;
    case "HouseQuote":
      w.string(b.pair); w.option(b.bid, (x) => pair(w, x)); w.option(b.ask, (x) => pair(w, x)); w.u64(b.valid_until); break;
    case "BuyBudget": w.u64(b.actions); break;
    case "CreateOffer": offerSpec(w, b as OfferSpec); break;
    case "UpdateOffer": w.u64(b.offer_id); offerSpec(w, b.spec); break;
    case "PauseOffer": w.u64(b.offer_id); w.bool(b.paused); break;
    case "CloseOffer": w.u64(b.offer_id); break;
    case "StartTrade": w.u64(b.offer_id); w.u128(b.amount); w.u128(b.fiat_amount); hash(w, b.instructions_hash); break;
    case "MarkPaid": w.u64(b.trade_id); w.option(b.proof_hash, (h) => hash(w, h)); break;
    case "ReleaseTrade": case "CancelTrade": w.u64(b.trade_id); break;
    case "OpenDispute": case "SubmitEvidence": w.u64(b.trade_id); hash(w, b.evidence_hash); break;
    case "RuleDispute": {
      w.u64(b.trade_id);
      const [r, rb] = variantOf(b.ruling);
      if (r === "WinsSeller") w.u8(0);
      else if (r === "WinsBuyer") w.u8(1);
      else if (r === "Split") { w.u8(2); w.u16((rb as any).buyer_bps); }
      else throw new Error(`unknown ruling ${r}`);
      break;
    }
    case "RequestDepositAddress": unitEnum(w, CHAINS, b.chain); break;
    case "ObserveDeposit":
      unitEnum(w, CHAINS, b.chain); w.string(b.asset); hash(w, b.tx_hash); w.u32(b.index); w.u64(b.deposit_index);
      w.u128(b.amount); w.u64(b.external_height); w.u64(b.tip_height); proof(w, b.proof);
      break;
    case "ObserveOutbound":
      w.u64(b.outbound_id); hash(w, b.tx_hash); w.u64(b.external_height); w.u64(b.tip_height); w.u128(b.fee_paid); w.bool(b.success);
      break;
    case "ReportNetworkFee": unitEnum(w, CHAINS, b.chain); w.u64(b.fee_rate); break;
    case "Withdraw": w.string(b.asset); w.string(b.to); w.u128(b.amount); break;
    case "RegisterVault":
      unitEnum(w, CHAINS, b.chain); w.u64(b.epoch); w.vecU8(toBytes(b.public_key)); w.option(b.chain_code, (h) => hash(w, h));
      w.vec(b.signers as Address[], (s) => address(w, s)); w.u32(b.threshold);
      break;
    case "MintStable": case "BurnStable": w.string(b.asset); w.u128(b.amount); break;
    case "Bond": unitEnum(w, ROLES, b.role); w.u128(b.amount); w.option(b.consensus_key, (h) => hash(w, h)); break;
    case "Unbond": unitEnum(w, ROLES, b.role); w.u128(b.amount); break;
    case "Delegate": case "Undelegate": address(w, b.validator); w.u128(b.amount); break;
    case "ClaimRewards": break;
    case "Propose": w.string(b.title); w.string(b.description); proposalKind(w, b.kind); break;
    case "Vote": w.u64(b.proposal_id); unitEnum(w, VOTES, b.choice); break;
    case "ExecuteProposal": w.u64(b.proposal_id); break;
    case "Attest": address(w, b.subject); w.u8(b.tier); w.u64(b.expires_at); break;
    case "SetParam": w.string(b.key); w.u128(b.value); break;
    case "LockBudget": w.u128(b.amount); break;
    case "UnlockBudget": w.u128(b.amount); break;
    case "AuthorizeSessionKey": address(w, b.key); w.u32(b.scope); w.u64(b.expires_at); break;
    case "RevokeSessionKey": address(w, b.key); break;
    case "RegisterLightningNode": w.vecU8(toBytes(b.node_id)); break;
    case "ObserveLightningDeposit": w.string(b.invoice); w.fixed(toBytes(b.preimage), 32); w.u64(b.amount_msat); break;
    case "ObserveLightningPayout": w.u64(b.outbound_id); w.option(b.preimage, (x) => w.fixed(toBytes(x), 32)); w.u64(b.fee_paid_msat); w.bool(b.success); break;
    case "FundLightningPool": w.u128(b.amount); w.string(b.to); break;
    case "AnnounceLightningSweep": w.fixed(toBytes(b.tx_hash), 32); w.u128(b.amount); break;
    case "SetClientFee": w.u32(b.p2p_bps); w.u32(b.taker_bps); w.u32(b.withdraw_bps); break;
    case "RegisterCustodyVault":
      unitEnum(w, CHAINS, b.chain); w.u64(b.epoch); w.vecU8(toBytes(b.public_key)); w.option(b.chain_code, (h) => hash(w, h)); w.string(b.signer_url); break;
    case "RequestCustodyAddress": unitEnum(w, CHAINS, b.chain); address(w, b.custodian); break;
    case "ObserveCustodyDeposit": {
      address(w, b.custodian); const o = b.observation as DepositObservation;
      unitEnum(w, CHAINS, o.chain); w.string(o.asset); hash(w, o.tx_hash); w.u32(o.index); w.u64(o.deposit_index);
      w.u128(o.amount); w.u64(o.external_height); w.u64(o.tip_height); proof(w, o.proof);
      break;
    }
    case "WithdrawCustody": w.string(b.asset); w.string(b.to); w.u128(b.amount); break;
    default: throw new Error(`unknown action ${name}`);
  }
  return w;
}
