//! Non-hardened BIP32 derivation from a vault's (public key, chain code).
//! The TSS key generated by CGGMP21 with HD support is exactly a BIP32
//! parent: children are `parent + I_L·G` with `I = HMAC-SHA512(chain_code,
//! ser_P(parent) || ser32(i))`, so any node can derive deposit addresses.

use crate::Error;
use bitcoin::bip32::{ChainCode, ChildNumber, Fingerprint, Xpub};
use bitcoin::secp256k1::{PublicKey, Secp256k1};
use bitcoin::NetworkKind;
use keel_actions::Chain;

/// SLIP-44 coin index used as the first path element per chain.
pub fn chain_index(chain: Chain) -> u32 {
    match chain {
        Chain::Bitcoin => 0,
        Chain::Ethereum => 60,
        Chain::Tron => 195,
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DerivedKey {
    pub public_key: [u8; 33],
    pub chain_code: [u8; 32],
}

impl DerivedKey {
    pub fn secp(&self) -> Result<PublicKey, Error> {
        PublicKey::from_slice(&self.public_key).map_err(|e| Error::Key(e.to_string()))
    }
}

fn synthetic_xpub(vault_pubkey: &[u8; 33], chain_code: &[u8; 32]) -> Result<Xpub, Error> {
    Ok(Xpub {
        network: NetworkKind::Main,
        depth: 0,
        parent_fingerprint: Fingerprint::default(),
        child_number: ChildNumber::from_normal_idx(0).map_err(|e| Error::Key(e.to_string()))?,
        public_key: PublicKey::from_slice(vault_pubkey).map_err(|e| Error::Key(e.to_string()))?,
        chain_code: ChainCode::from(*chain_code),
    })
}

/// Derive the non-hardened child at `path` (every element < 2^31).
pub fn child_pubkey(
    vault_pubkey: &[u8; 33],
    chain_code: &[u8; 32],
    path: &[u32],
) -> Result<DerivedKey, Error> {
    let secp = Secp256k1::verification_only();
    let mut xpub = synthetic_xpub(vault_pubkey, chain_code)?;
    for idx in path {
        let child = ChildNumber::from_normal_idx(*idx).map_err(|e| Error::Key(e.to_string()))?;
        xpub = xpub
            .ckd_pub(&secp, child)
            .map_err(|e| Error::Key(e.to_string()))?;
    }
    Ok(DerivedKey {
        public_key: xpub.public_key.serialize(),
        chain_code: xpub.chain_code.to_bytes(),
    })
}

/// The path of deposit index `index` on `chain`: `m/<slip44>/<index>`.
/// Indexes above 2^31 are split across two levels so nothing is hardened.
pub fn deposit_path(chain: Chain, index: u64) -> Vec<u32> {
    let hi = (index >> 31) as u32;
    let lo = (index & 0x7fff_ffff) as u32;
    if hi == 0 {
        vec![chain_index(chain), lo]
    } else {
        vec![chain_index(chain), hi, lo]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    /// BIP32 test vector 1: m/0H is a known xpub; its non-hardened child 1
    /// must match the published m/0H/1 xpub, and our synthetic-xpub
    /// derivation must agree with the crate's own.
    #[test]
    fn matches_bip32_vector_1() {
        let m0h = Xpub::from_str("xpub68Gmy5EdvgibQVfPdqkBBCHxA5htiqg55crXYuXoQRKfDBFA1WEjWgP6LHhwBZeNK1VTsfTFUHCdrfp1bgwQ9xv5ski8PX9rL2dZXvgGDnw").unwrap();
        let expected = Xpub::from_str("xpub6ASuArnXKPbfEwhqN6e3mwBcDTgzisQN1wXN9BJcM47sSikHjJf3UFHKkNAWbWMiGj7Wf5uMash7SyYq527Hqck2AxYysAA7xmALppuCkwQ").unwrap();
        let derived = child_pubkey(
            &m0h.public_key.serialize(),
            &m0h.chain_code.to_bytes(),
            &[1],
        )
        .unwrap();
        assert_eq!(derived.public_key, expected.public_key.serialize());
        assert_eq!(derived.chain_code, expected.chain_code.to_bytes());
        // Two levels compose.
        let two = child_pubkey(
            &m0h.public_key.serialize(),
            &m0h.chain_code.to_bytes(),
            &[1, 2],
        )
        .unwrap();
        let secp = Secp256k1::verification_only();
        let via_crate = expected
            .ckd_pub(&secp, ChildNumber::from_normal_idx(2).unwrap())
            .unwrap();
        assert_eq!(two.public_key, via_crate.public_key.serialize());
    }

    #[test]
    fn hardened_indexes_are_rejected_and_big_indexes_split() {
        let m0h = Xpub::from_str("xpub68Gmy5EdvgibQVfPdqkBBCHxA5htiqg55crXYuXoQRKfDBFA1WEjWgP6LHhwBZeNK1VTsfTFUHCdrfp1bgwQ9xv5ski8PX9rL2dZXvgGDnw").unwrap();
        assert!(child_pubkey(
            &m0h.public_key.serialize(),
            &m0h.chain_code.to_bytes(),
            &[1 << 31]
        )
        .is_err());
        assert_eq!(deposit_path(Chain::Bitcoin, 7), vec![0, 7]);
        assert_eq!(deposit_path(Chain::Tron, (1 << 31) + 5), vec![195, 1, 5]);
    }
}
